# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-02-03 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='Enter the group musical name', max_length=128),
        ),
        migrations.AlterField(
            model_name='membership',
            name='actived',
            field=models.BooleanField(default=True, help_text='This membership is actived?'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateField(help_text='The date that membership was made.'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(help_text='Select a group musical from the list.', on_delete=django.db.models.deletion.CASCADE, to='myapp.Group'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='invite_reason',
            field=models.CharField(help_text='Enter the invite reason to this group musical.', max_length=64),
        ),
        migrations.AlterField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(help_text='Select a musician from the list.', on_delete=django.db.models.deletion.CASCADE, to='myapp.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Enter the musician name of group musical', max_length=128),
        ),
    ]
